{{ config(
    database='DBT_STAGING',
    tags=["stocks_batch"] 
) }}

SELECT
DATE
,TICKER
,ROUND(OPEN) AS OPEN
,ROUND(HIGH) AS HIGH
,ROUND(LOW) AS LOW
,ROUND(CLOSE) AS CLOSE
,VOLUME
FROM
DBT_RAW.LANDING_ZONE.BATCH_DATA_STOCKS
