{{ config(
    database='SMANTRI',
    tags=["stocks_streaming"],
    pre_hook="ALTER EXTERNAL TABLE SMANTRI.LANDING_ZONE.INTRADAY_STREAMING REFRESH" 
) }}

SELECT
SYMBOL
,TO_TIMESTAMP(TIMESTAMP) AS INGESTED_TIME
,ROUND(OPEN) AS OPEN
,ROUND(HIGH) AS HIGH
,ROUND(LOW) AS LOW
,ROUND(CLOSE) AS CLOSE
,VOLUME
FROM
SMANTRI.LANDING_ZONE.INTRADAY_STREAMING
