{{ config(
    database='SMANTRI',
    tags=["stocks_batch"]
) }}

--rolling 52 weeks high


WITH MAX_HIGH AS (
SELECT 
ROUND(MAX(HIGH)) AS MAX_HIGH
,TICKER 
FROM {{ ref('YAHOO_STOCKS_BATCH_DATA') }}
WHERE DATE>=CURRENT_DATE - (365*2)
GROUP BY 2),

INCLUDE_DATES AS
(SELECT 
M.TICKER
,B.DATE
,M.MAX_HIGH 
FROM 
{{ ref('YAHOO_STOCKS_BATCH_DATA') }} B
INNER JOIN
MAX_HIGH M
ON
ROUND(B.HIGH)=ROUND(M.MAX_HIGH)
AND
B.TICKER=M.TICKER)

SELECT DISTINCT * FROM INCLUDE_DATES ORDER BY TICKER ASC, DATE ASC
