{{ config(
    database='SMANTRI',
    tags=["stocks_batch"]
) }}

WITH MIN_LOW AS (
SELECT 
ROUND(MIN(LOW)) AS MIN_LOW
,TICKER 
FROM {{ ref('YAHOO_STOCKS_BATCH_DATA') }}
WHERE DATE>=CURRENT_DATE - (365*2)
GROUP BY 2),

INCLUDE_DATES AS
(SELECT 
M.TICKER
,B.DATE
,M.MIN_LOW 
FROM 
{{ ref('YAHOO_STOCKS_BATCH_DATA') }} B
INNER JOIN
MIN_LOW M
ON
ROUND(B.LOW)=ROUND(M.MIN_LOW)
AND
B.TICKER=M.TICKER)

SELECT DISTINCT * FROM INCLUDE_DATES ORDER BY TICKER ASC, DATE ASC
